version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  # reviewers:
  # - "wandera/<github-team-name>"
  commit-message:
    prefix: "TRIVIAL: "
